# JDBC connection
spring.datasource.url=jdbc:postgresql://localhost:5433/ticketdb
spring.datasource.username=postgres
spring.datasource.password=Nikutopus@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

# Server port
server.port=8080




#DOCKER____
#spring.datasource.url=jdbc:postgresql://postgres:5432/ticketdb
#spring.datasource.username=postgres
#spring.datasource.password=Nikutopus@123
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.sql.init.mode=always
#server.port=8080

